# Generated by Django 5.0.7 on 2024-07-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Enter the name of the product", max_length=255
                    ),
                ),
                (
                    "product_quantity",
                    models.PositiveIntegerField(
                        help_text="Enter the quantity of the product"
                    ),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the price of the product",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wgql.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_url",
                    models.ImageField(
                        help_text="Select the product images",
                        upload_to="product_images/",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wgql.product"
                    ),
                ),
            ],
        ),
    ]
