# Generated by Django 5.0.7 on 2024-07-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wgql", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wgql.order",
            ),
        ),
    ]
