# Generated by Django 5.0.7 on 2024-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wgql", "0002_alter_product_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.CharField(default="", max_length=120),
        ),
    ]
