# Generated by Django 5.0.7 on 2024-07-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_image_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Order Created Date"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                help_text="Select the product image",
                upload_to="products/",
                verbose_name="Product Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Enter the name of the product",
                max_length=255,
                verbose_name="Product Name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Enter the price of the product",
                max_digits=5,
                verbose_name="Product Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(
                default=1,
                help_text="Enter the quantity of the product",
                verbose_name="Product Quantity",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.order",
                verbose_name="Order",
            ),
        ),
    ]
