# Generated by Django 5.0.7 on 2024-07-11 14:13

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_order_alter_image_image_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                help_text="Select the product image",
                upload_to=app.models.get_image_path,
                verbose_name="Product Image",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.product",
            ),
        ),
    ]
