# Generated by Django 5.0.7 on 2024-07-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_image_image_alter_image_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="app.order",
                verbose_name="Order",
            ),
        ),
    ]
